### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by orhanveli** [tuananh/camaro#55]
Hello 
Do you have any plan to suppoert ARM CPU support? 

I have an ARM chipset box and running Armbian Ubuntu on it but I can't run my camaro dependent project on it.

Here is the ``docker-compose build`` logs

```
Step 6/8 : RUN npm install &&     npm cache clean --force
 ---> Running in b296051d19b0

> camaro@3.0.14 install /usr/app/node_modules/camaro
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/tuananh/camaro/releases/download/3.0.14/camaro-v3.0.14-node-v64-linux-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for camaro@3.0.14 and node@10.15.0 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
gyp ERR! System Linux 4.20.2-aml-s905
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/app/node_modules/camaro/lib/binding/camaro.node" "--module_name=camaro" "--module_path=/usr/app/node_modules/camaro/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/app/node_modules/camaro
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/app/node_modules/camaro/lib/binding/camaro.node --module_name=camaro --module_path=/usr/app/node_modules/camaro/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.20.2-aml-s905
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/app/node_modules/camaro
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/app/node_modules/camaro/lib/binding/camaro.node --module_name=camaro --module_path=/usr/app/node_modules/camaro/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN camaro@3.0.14 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! camaro@3.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the camaro@3.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-03T20_31_28_227Z-debug.log
```

**Comment by tuananh** [comment]
@orhanveli i'll look into it. right now, the prebuilt binary are built via appveyor and travis. I'm not sure if they support arm or not.

**Comment by tuananh** [comment]
i added arm build on appveyor (win). will look into arm on linux later this week.https://github.com/tuananh/camaro/releases/tag/3.0.15

**Comment by orhanveli** [comment]
great news I'm looking fw :)

**Comment by tuananh** [comment]
@orhanveli you can also try `npm i camaro@next` to try the wasm. since it's wasm, it will work on all platform.

**Comment by tuananh** [comment]
Closing with https://github.com/tuananh/camaro/pull/64
